CREATE TABLE `SYS_USER` (
  `USR_UID` varchar(36) PRIMARY KEY COMMENT 'UserID',
  `USR_USERNAME` varchar(50),
  `USR_PWD` varchar(100),
  `USR_ROLE` varchar(20),
  `USR_FIRSTNAME` varchar(200),
  `USR_LASTNAME` varchar(200),
  `USR_CREATEDATE` datetime
);

CREATE TABLE `SYS_ROLE` (
  `RLS_ROLE` varchar(20) PRIMARY KEY
);

CREATE TABLE `SYS_TOKEN` (
  `TKN_UID` varchar(36) PRIMARY KEY COMMENT 'UserID',
  `TKN_TOKEN` varchar(100),
  `TKN_CREATEDATE` datetime,
  `TKN_EXPIRE` datetime
);

CREATE TABLE `MST_TASK_TYPE` (
  `TKT_ID` int PRIMARY KEY AUTO_INCREMENT,
  `TKT_TYPE_NAME` varchar(50),
  `TKT_CREATEDATE` datetime,
  `TKT_LASTUPDATE` datetime
);

CREATE TABLE `DAT_TASK` (
  `DTK_ID` int PRIMARY KEY AUTO_INCREMENT,
  `DTK_TASK_NAME` varchar(100),
  `DTK_TKT_ID` int,
  `DTK_PRIORITY` int,
  `DTK_CREATEDATE` datetime,
  `DTK_DURATION` int,
  `DTK_DURATION_TYPE` ENUM ('NULL', 'HOUR', 'DAY'),
  `DTK_DESCRIPTION` varchar(250),
  `DTK_CREATE_BY_UID` varchar(32),
  `DTK_ASSIGN_TO_UID` varchar(32),
  `DTK_STATUS` ENUM ('PREVIEW', 'ASSIGNED', 'PROCESSING', 'COMPLETE'),
  `DTK_COMPLETE` bit
);

ALTER TABLE `SYS_TOKEN` ADD FOREIGN KEY (`TKN_UID`) REFERENCES `SYS_USER` (`USR_UID`);

ALTER TABLE `SYS_USER` ADD FOREIGN KEY (`USR_ROLE`) REFERENCES `SYS_ROLE` (`RLS_ROLE`);

-- ALTER TABLE `DAT_TASK` ADD FOREIGN KEY (`DTK_CREATE_BY_UID`) REFERENCES `SYS_USER` (`USR_UID`);

-- ALTER TABLE `DAT_TASK` ADD FOREIGN KEY (`DTK_ASSIGN_TO_UID`) REFERENCES `SYS_USER` (`USR_UID`);

-- ALTER TABLE `DAT_TASK` ADD FOREIGN KEY (`DTK_TKT_ID`) REFERENCES `MST_TASK_TYPE` (`TKT_ID`);
