# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: fse@2022
    ports:
      - 3306:3306
    volumes:
      - '/dbdata:/var/lib/mysql'    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080